"""The three upstream dailies: locate today's file, parse it, strip ops content.

Contracts for each upstream live in ../contracts/.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field

from . import config
from .config import FINANCE_OPS_HEADINGS, KLINE_OPS_HEADINGS, macro_key
from .text import drop_first_h1, md_to_html, short_date, strip_front_matter


@dataclass
class Section:
    key: str
    title: str
    status: str = "missing"  # ok | missing | unavailable
    reason: str = ""
    html: str = ""
    meta: dict = field(default_factory=dict)


def load_ai(date: str) -> Section:
    sec = Section("ai", "AI 日报")
    path = config.AI_DIR / f"{short_date(date)}.md"
    if not path.exists():
        sec.reason = f"未找到 {path.name}"
        return sec
    text = drop_first_h1(path.read_text(encoding="utf-8"))
    sec.status, sec.html = "ok", md_to_html(text)
    top = re.search(r"^### \[(.+?)\]\(", text, flags=re.M) or re.search(r"^- \*\*.+?\*\* \| \[(.+?)\]\(", text, flags=re.M)
    sec.meta = {"path": str(path), "items": len(re.findall(r"^- \*\*", text, flags=re.M)), "top": top.group(1) if top else ""}
    return sec


def clean_finance_md(body: str) -> str:
    """Reader-facing finance brief: drop ops sections, generator lines and the UTC window header."""
    body = drop_first_h1(body).replace("Generated by Park Intel.", "")
    # remove ops sections (## heading … up to next ## or end)
    for heading in FINANCE_OPS_HEADINGS:
        body = re.sub(rf"^## {re.escape(heading)}\n.*?(?=^## |\Z)", "", body, flags=re.S | re.M)
    body = re.sub(r"^Processing Status:\n(?:- .*\n?)+", "", body, flags=re.M)
    body = re.sub(r"^🎯 Daily Trader Brief.*$", "", body, flags=re.M)
    body = re.sub(r"^覆盖窗口：.*$", "", body, flags=re.M)
    body = re.sub(r"^---\s*$", "", body, flags=re.M)
    body = re.sub(r"\n{3,}", "\n\n", body)
    return body.strip()


def load_finance(date: str) -> Section:
    sec = Section("finance", "财经日报")
    path = config.FIN_DIR / f"{date}-finance-daily-newsletter.md"
    if not path.exists():
        sec.reason = f"未找到 {path.name}"
        return sec
    meta, body = strip_front_matter(path.read_text(encoding="utf-8"))
    body = clean_finance_md(body)
    sec.status, sec.html = "ok", md_to_html(body)
    heads = re.findall(r"^## (.+)$", body, flags=re.M)
    first = re.search(r"^\d+\. \*\*(.+?)\*\*", body, flags=re.M)
    sec.meta = {"path": str(path), "articles": meta.get("article_count"), "signals": meta.get("signal_count"), "sections": heads, "top": first.group(1) if first else ""}
    return sec


def parse_asset_chunk(chunk: str) -> dict:
    lines = chunk.strip().splitlines()
    name = lines[0].strip()
    ticker, as_of, fields = "", "", {}
    for line in lines[1:]:
        line = line.strip()
        if line.startswith("标的："):
            ticker = line[3:].strip()
        elif line.startswith("观察时点："):
            as_of = line[5:].strip()[:10]
        else:
            fm = re.match(r"\*\*(.+?)\*\*[：:]\s*(.*)", line)
            if fm:
                label, value = fm.group(1), fm.group(2)
                value = re.sub(rf"^{re.escape(label)}[：:]\s*", "", value).strip()
                if label == "赔率" and "尚未形成" in value:
                    continue  # boilerplate; show 赔率 only when it says something
                if label == "市场含义":
                    continue  # identical every day; not reader-facing
                if value:
                    fields[label] = value
    return {"name": name, "ticker": ticker, "as_of": as_of, "fields": fields, "key": macro_key(name, ticker)}


def parse_kline_md(text: str) -> dict:
    """Split the K-line newsletter into summary sections, the 16 asset blocks, treasury blocks; drop ops."""
    _, body = strip_front_matter(text)
    body = drop_first_h1(body)
    for heading in KLINE_OPS_HEADINGS:
        body = re.sub(rf"^## {re.escape(heading)}\n.*?(?=^## |\Z)", "", body, flags=re.S | re.M)
    split = re.search(r"^## 共有.*$", body, flags=re.M)
    summary_md = (body[: split.start()] if split else body).strip()
    summary: dict[str, str] = {}
    for m in re.finditer(r"^## (.+?)\n(.*?)(?=^## |\Z)", summary_md, flags=re.S | re.M):
        summary[m.group(1).strip()] = m.group(2).strip()
    assets, treasuries = [], []
    if split:
        rest = body[split.end():]
        tre = re.search(r"^## 美国国债.*$", rest, flags=re.M)
        main_part, tre_part = (rest[: tre.start()], rest[tre.end():]) if tre else (rest, "")
        assets = [parse_asset_chunk(c) for c in re.split(r"^### ", main_part, flags=re.M)[1:]]
        treasuries = [parse_asset_chunk(c) for c in re.split(r"^### ", tre_part, flags=re.M)[1:]]
    conclusion = ""
    cm = re.match(r"\*\*(.+?)\*\*\s*·?\s*(.*)", summary.get("今日结论", ""), flags=re.S)
    if cm:
        conclusion = f"{cm.group(1)} · {cm.group(2).splitlines()[0]}".strip(" ·")
    return {"summary_md": summary_md, "summary": summary, "assets": assets, "treasuries": treasuries, "conclusion": conclusion}


def load_kline(date: str) -> tuple[Section, dict]:
    sec = Section("kline", "K 线日报")
    path = config.KL_DIR / f"{date}-kline-daily-newsletter.md"
    parsed = {"summary_md": "", "summary": {}, "assets": [], "treasuries": [], "conclusion": ""}
    if path.exists():
        parsed = parse_kline_md(path.read_text(encoding="utf-8"))
        sec.status = "ok"
        sec.meta = {"path": str(path), "assets": len(parsed["assets"])}
        return sec, parsed
    unavailable = config.KL_DIR / f"{date}-kline-daily-newsletter-unavailable.md"
    if unavailable.exists():
        text = unavailable.read_text(encoding="utf-8")
        reason = re.search(r"失败原因：(.*)", text)
        stage = re.search(r"运行阶段：(.*)", text)
        sec.status = "unavailable"
        sec.reason = f"{(stage.group(1) if stage else '')} · {(reason.group(1) if reason else '管道未生成')}".strip(" ·")
    else:
        sec.reason = f"未找到 {path.name}"
    return sec, parsed


def load_park_notes(date: str) -> dict[str, str]:
    """## KEY sections keyed by ticker / symbol / name; '## 总' is the overall note."""
    path = config.PARK_DIR / f"{date}.md"
    if not path.exists():
        return {}
    notes: dict[str, str] = {}
    current = None
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^##\s+(.+?)\s*$", line)
        if m:
            current = m.group(1).strip()
            notes[current] = ""
        elif current is not None:
            notes[current] = (notes[current] + "\n" + line).strip()
    return {k: v for k, v in notes.items() if v}
